### ISSUE TITLE
Backend warnings about deprecated pandas feature

### ISSUE THREAD

**Issue by austinjpaul** [transitmatters/t-performance-dash#155]
`server/chalicelib/aggregation.py:92: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.`

same thing for lines 92, 148, and 180

**Comment by devinmatte** [comment]
Probably a prerequisite for #436

**Comment by devinmatte** [comment]
This looks done in both main and dashboard-v4
