### ISSUE TITLE
Graph x range is not always a full day

### ISSUE THREAD

**Issue by mathcolo** [transitmatters/t-performance-dash#2]
Even if the time scale of data available from the MBTA performance API is not a full day, would be helpful for that to be clear in the chart by having the X range always be 6am-1am.

**Comment by austinjpaul** [comment]
Relatedly, it would be nice to force the x axis to the selected range in agg mode also, even if there's no data

**Comment by austinjpaul** [comment]
Not a good first issue. I tried. I failed.
setting min: and max: in a ticks field under the xaxes in Line should do the trick, but it wasn't working for me. maybe i don't have the time format right (should be different for agg and non-agg).
but ALSO
this will probably affect the chartTimeFrame func used to plot the alert bar- right now that's pulling from the data, knowing the chart will adjust to fit all.
This leads to some discrepancies currently where we dont have traveltime data, but do have dwells e.g.
