### ISSUE TITLE
License on code?

### ISSUE THREAD

**Issue by ianhi** [transitmatters/t-performance-dash#252]
Hi,

There doesn't seem to be a license file anywhere obvious - what license should I assume the code in this repo is under?

I'd like to incorporate the very helpful information in the [bus_constants](https://github.com/transitmatters/t-performance-dash/tree/main/src/bus_constants) folder into my small python package (https://github.com/ianhi/mbta-analysis) I've been creating in order to make plots that can't easily be made on the dashboard (e.g. put different bus lines on the same y-axis).

thanks,
ian

**Comment by nathan-weinberg** [comment]
Hi @ianhi,

The LICENSE is in the `docs` directory, same as the `README`

Feel free to reach out to labs@transitmatters.org and we can discuss further!

Best,
Nathan

**Comment by ianhi** [comment]
Ah gotcha - can I suggest moving that to the top level so that github auto recognizes it and puts in the sidebar? And/or adding a licence badge to the top of the readme. Looking in the docs directory was non-intuitive for me when looking for a license.

**Comment by nathan-weinberg** [comment]
@ianhi we are discussing internally now! thanks for bringing it to our attention
