### ISSUE TITLE
Feedback button

### ISSUE THREAD

**Issue by austinjpaul** [transitmatters/t-performance-dash#31]
Would be nice if we had a way for folks to reach the team with feedback, e.g. colorblindness accessibility complaints.

**Comment by nathan-weinberg** [comment]
How do we want feedback to be structured - GitHub Issues may not be good for the public as I assume most folks don't have GitHub accounts. Maybe a simple `mailto` for a feedback email address?

**Comment by nathan-weinberg** [comment]
From meeting notes:
- White button that stands out in UI
- Button should do mailto to labs email with subject “Feedback - [hostname]”
