### ISSUE TITLE
Fix links in deployed V4

### ISSUE THREAD

**Issue by PatrickCleary** [transitmatters/t-performance-dash#349]
When the v4 dashboards are deployed. None of the links work, they all lead to the root `/`. 

This is the problem (but the proposed solution does not work)
https://stackoverflow.com/questions/57438566/next-js-export-static-s3-routing-fails-on-page-reload

**Comment by devinmatte** [comment]
@mathcolo I think you may be of help here, this might be a s3 thing, or it may be a nextjs consequence. We also give up features by exporting as a static site that we may want to avoid

**Comment by skaplan-dev** [comment]
@mathcolo We think that s3 might be limiting for our next js router setup. We were thinking about AWS amplify and trying to do some cost analysis. We can deploy from our GitHub branch, but we need to allow `read` writes for AWS Amplify onto the repo. Any chance you could help with that?
