### ISSUE TITLE
Date Picker fix

### ISSUE THREAD

**Issue by PatrickCleary** [transitmatters/t-performance-dash#369]
If the user is in "single day" mode then the last _x_ days selector won't choose a range, it only chooses the first date in that range. The reverse is also true - if you're looking at aggregates and select "today" or "yesterday" it makes a one day range.

**Comment by devinmatte** [comment]
I think we can modify the preset list on the picker, so we have different options for single vs aggregate (today and yesterday don't make sense on aggregate, and for single it should be `one month ago` instead of `last month`

**Comment by devinmatte** [comment]
In 1.5.1 of the library my changes are available which allow us to hide certain presets based on props. We can fix this now
