### ISSUE TITLE
Improve loading + Transitions

### ISSUE THREAD

**Issue by PatrickCleary** [transitmatters/t-performance-dash#372]
When clicking between pages, there is no visual indicator that the action was completed until the new page loads. Would be good to do the following 3 things while loading:
1. change the tab highlight 
2. clear the current dashboard
3. show some sort of loading screen

**Comment by PatrickCleary** [comment]
I think this is only an issue in development actually. NextJS compiles pages lazily

**Comment by devinmatte** [comment]
This seems done to me

**Comment by PatrickCleary** [comment]
yes
