### ISSUE TITLE
Show information about accessibility and bike storage in station selector

### ISSUE THREAD

**Issue by devinmatte** [transitmatters/t-performance-dash#375]
It would be nice if we had the list of accessible stations and bike storage that we could display in relevant interfaces

**Comment by mxmeinhold** [comment]
Starting to experiment with this, all the info is pretty readily available from the v3 api, though I'm not sure yet how to surface it to the UI 
my branch: https://github.com/mxmeinhold/t-performance-dash/tree/wheelchair-and-bike

**Comment by devinmatte** [comment]
I was doing some amount of it in v4. If the data is in the API that's better than what I was doing with manual input
