### ISSUE TITLE
Store Alerts in s3

### ISSUE THREAD

**Issue by austinjpaul** [transitmatters/t-performance-dash#39]
a) so we don't lose them after 90 days, and 
b) to improve query time

**Comment by austinjpaul** [comment]
alternatively, query twitter for tweets?

**Comment by mathcolo** [comment]
This is in as of https://github.com/transitmatters/t-performance-dash/pull/41, and it should generally work.

Timezone mixture might be a little strange, though. We download new data from the T at 10am UTC (5am EST), but at 4am EST, it's still "today" in UTC and EST. That means requests for "yesterday" will come from our storage, but they won't have been downloaded yet...

Some options might be
a) Run the cron at 12:01am ET (not sure setting this to ET is actually possible?), but not sure if MBTA-performance `pastalerts` are actually populated yet
b) Use MBTA-performance for today and yesterday to smooth over the problem?

**Comment by austinjpaul** [comment]
This is a weird thing. Can't we check 'today-ness' using EST? I'm probably misunderstanding the issue.
In any case, I like option B - nice and simple.

**Comment by friendchris** [comment]
The issue is likely also that “transit-days” run from 3:30AM ET. So if you’re calling the job you want to call it from 3:30:01AM previous day to 3:30:00AM the next day.
