### ISSUE TITLE
Historical Alerts on Trips Pages

### ISSUE THREAD

**Issue by devinmatte** [transitmatters/t-performance-dash#406]
Just like in v3, we should show historical alerts over details graphs to help align bumps in data with what was communicated to riders

**Comment by PatrickCleary** [comment]
I propose we skip this for launch unless someone feels strongly otherwise.

**Comment by devinmatte** [comment]
I don't think we should skip this. It shouldn't be too hard to implement since we'd be using the same API as v3

**Comment by devinmatte** [comment]
I'll take a look into this today
