### ISSUE TITLE
Finish Line Landing page

### ISSUE THREAD

**Issue by PatrickCleary** [transitmatters/t-performance-dash#421]
https://transitmatters.slack.com/archives/GSJ6F35DW/p1677883363704789

Something for todays commute similar to speed metric

**Comment by mcplanner** [comment]
Assigned to Ruth to describe new design.

**Comment by mcplanner** [comment]
No date selection on this view. The user gets to pick the dates after they click through.

**Comment by mcplanner** [comment]
New designs with lots of comments in [Figma](https://www.figma.com/file/bLBzzBX3r6tG2CoS6vWglD/Dashboard---V4?type=design&node-id=46-6603&t=YOyaJ87Wb4i0Emb2-0).
