### ISSUE TITLE
SZ line graph (all lines)

### ISSUE THREAD

**Issue by PatrickCleary** [transitmatters/t-performance-dash#424]
Equivalent of this for V4

https://dashboard.transitmatters.org/slowzones

**Comment by devinmatte** [comment]
We have this now, but ideally we would add more options like we had in v3 (line toggles) and the segment graph for all lines

**Comment by nathan-weinberg** [comment]
Think this is done now yes?

**Comment by devinmatte** [comment]
It could be considered done yeah. We could improve it, but I'd say sufficiently done
