### ISSUE TITLE
Link conversion from v3 -> v4

### ISSUE THREAD

**Issue by PatrickCleary** [transitmatters/t-performance-dash#428]
Middleware to convert V3 links to V4

**Comment by devinmatte** [comment]
We still need to handle `/slowzones`

**Comment by devinmatte** [comment]
Middleware doesn't seem to be working in beta right now: https://dashboard-v4-beta.labs.transitmatters.org/rapidtransit?config=Blue,70051,70039,2023-06-12,
It just seems to drop you on the 404 page

**Comment by PatrickCleary** [comment]
But it works locally right? Did we ever test in beta?

**Comment by devinmatte** [comment]
Yep works locally, so this may not work in static bundles

**Comment by PatrickCleary** [comment]
Whoops 😔
![Screen Shot 2023-06-15 at 1 27 44 PM](https://github.com/transitmatters/t-performance-dash/assets/46229349/fd7a5af0-9d1f-4276-8125-5e8f7d14a430)

**Comment by PatrickCleary** [comment]
Also doesn't include redirects and headers. Is there any way to fix this without those...?

**Comment by devinmatte** [comment]
Yeah. I'll have to take a look at this again. We may have to manually handle this by making routes and using browser redirects
