### ISSUE TITLE
Display properly when station pair returns no data

### ISSUE THREAD

**Issue by devinmatte** [transitmatters/t-performance-dash#471]
**In v3 we showed**
<img width="1035" alt="Screenshot 2023-04-10 at 5 30 39 PM" src="https://user-images.githubusercontent.com/9310513/231002870-557f7858-1bca-4e4a-8885-aeb01b8a6af3.png">

In v4 we currently show
<img width="638" alt="Screenshot 2023-04-10 at 5 30 57 PM" src="https://user-images.githubusercontent.com/9310513/231002916-3613219f-d36d-481f-8f9b-f4e8ecf7ff68.png">

We should be clearer that there's no data to show

**Comment by PatrickCleary** [comment]
As a note for whoever is working on this, I _believe_ that the code to display this message is still here, but in most of our charts we are passing empty arrays which do not show this message. I believe it needs to receive undefined.

Another note is that some charts are using the `ChartPlaceholder` component and some are not. I believe the ones that are using the component would show an error message in this case. However if we want to differentiate between error and no data we could add some fairly simple logic to do so.
