### ISSUE TITLE
Slow zone map shrinks when switching lines

### ISSUE THREAD

**Issue by devinmatte** [transitmatters/t-performance-dash#494]
<img width="1225" alt="Screenshot 2023-04-14 at 3 07 32 PM" src="https://user-images.githubusercontent.com/9310513/232134691-639591d3-0e63-4ccd-ab8e-7c737e618858.png">
The slow zone map sometimes shrinks between line changes, and stays that way until a full page reload

**Comment by devinmatte** [comment]
This seems fixed now

**Comment by PatrickCleary** [comment]
Agreed
