### ISSUE TITLE
Bus page load by URL navigation bug

### ISSUE THREAD

**Issue by PatrickCleary** [transitmatters/t-performance-dash#497]
Navigating to a bus page by URL throws an error>

reproduce by going to this URL:

https://dashboard-v4-beta.labs.transitmatters.org/bus/trips/?busRoute=15&to=15-1-21148&from=15-1-1468&startDate=2022-12-31&queryType=single

No charts load. Same with any bus `trips` page.

Doesn't work when refreshing, but navigating to the same page within the app works fine.

**Comment by devinmatte** [comment]
Clicking that link worked fine
