### ISSUE TITLE
Update slow zone data daily

### ISSUE THREAD

**Issue by PatrickCleary** [transitmatters/t-performance-dash#537]
Currently it's only updated on deploymenets

**Comment by idreyn** [comment]
Maybe we should move this (and the speed restrictions script next door) to the `data-ingestion` repo.

**Comment by devinmatte** [comment]
It should be since the daily cron task uploads the results to the prod bucket at `/static/slowzones`. We probably should update the job to maybe put it in it's own bucket, but, it's not necessary
