### ISSUE TITLE
choose baselines

### ISSUE THREAD

**Issue by PatrickCleary** [transitmatters/t-performance-dash#547]
We want to keep our goals (typically system-peaks) relevant. A good way to do this will be to have a horizontal line on all graphs, expecially on the `line` page of the goal.

Discussed here:
https://transitmatters.slack.com/archives/GSJ6F35DW/p1683303947213649

Can maybe use this annotation plugin: https://www.chartjs.org/chartjs-plugin-annotation/latest/samples/intro.html

Or a new dataset with every entry set to the goal.

**Comment by PatrickCleary** [comment]
(choose a baseline for every metric)

**Comment by mcplanner** [comment]
In the future, TM could have an initiative to define meaningful goals for each metric. This would be a great event for social media.

**Comment by PatrickCleary** [comment]
Need to do buses still

**Comment by devinmatte** [comment]
Is there more work needed here?

**Comment by PatrickCleary** [comment]
I think we just need to change the word "Baseline" to "Peak" throughout @devinmatte
