### ISSUE TITLE
Default date selector to yesterday before ~6 AM

### ISSUE THREAD

**Issue by PatrickCleary** [transitmatters/t-performance-dash#570]
If you open the dashboard after 12 AM, the graphs all show today, but we probably want to show yesterday's values until we start receiving today's data.

**Comment by JNuss71** [comment]
Is the point of this to make "Today" continue to be the selection of yesterday's date between midnight and 6AM or to set the default to "Yesterday" between 12:00AM and ~6AM for single date presets like the "Trips" page?

**Comment by PatrickCleary** [comment]
I think setting the default to yesterday would be more intuitive.
