### ISSUE TITLE
Slow zone map shifting on mobile

### ISSUE THREAD

**Issue by devinmatte** [transitmatters/t-performance-dash#573]
![Screenshot_20230514-183735.png](https://github.com/transitmatters/t-performance-dash/assets/9310513/b4f43d7c-2550-4c20-b754-eb28c95793d0)

![Screenshot_20230514-183717.png](https://github.com/transitmatters/t-performance-dash/assets/9310513/6437ce52-520e-4eb7-bec4-561e88a8c616)

**Comment by PatrickCleary** [comment]
and other visual bugs
