### ISSUE TITLE
Make new hero image for TM Dashboard

### ISSUE THREAD

**Issue by mcplanner** [transitmatters/t-performance-dash#601]

**Comment by PatrickCleary** [comment]
Or could just make a new favicon right? That would kill two birds with one stone.

I started messing with some favicons but wasn't too happy with any of them. those are here: https://www.figma.com/file/bLBzzBX3r6tG2CoS6vWglD?node-id=439:10327#460614984

**Comment by PatrickCleary** [comment]
Oh this is the hero image, nvm

**Comment by mcplanner** [comment]
Thanks @PatrickCleary for the suggestion to use Fable!

[Dashboard.lottie.json.zip](https://github.com/transitmatters/t-performance-dash/files/11715490/Dashboard.lottie.json.zip)
