### ISSUE TITLE
Update service/ridership data sources

### ISSUE THREAD

**Issue by PatrickCleary** [transitmatters/t-performance-dash#609]
Making a ticket to track this.

Just want to make sure the data ingestion for service and ridership is up to date.

**Comment by idreyn** [comment]
- [ ] Backfill service to 2016
- [ ] Make sure jobs are succeeding nightly
- [ ] Check out missing GL ridership issue

**Comment by PatrickCleary** [comment]
@idreyn For aggregating GL and Bus data, are you planning on doing that on the backend and adding a new primary key for the aggregates?

**Comment by idreyn** [comment]
@PatrickCleary yes, probably. It'd just be a fake line_id like `Bus`.

**Comment by PatrickCleary** [comment]
Can you backfill ridership to 2016 as well?

**Comment by devinmatte** [comment]
Is there additional work needed here?

**Comment by PatrickCleary** [comment]
yes, ridership prior to 2018. Not a v4 blocker necessarily though.
