### ISSUE TITLE
Consolidate landing page text

### ISSUE THREAD

**Issue by PatrickCleary** [transitmatters/t-performance-dash#610]
My suggestion:

"America's fourth largest transit agency has been struggling.

Are things getting better? Let's find out."

**Comment by devinmatte** [comment]
How about "America's oldest transit system"?

**Comment by mcplanner** [comment]
Fair point, Devin. I personally prefer emphasizing how big the system is (or should be). The MBTA isn't some old timey vintage choo choo. The MBTA should be speaking with authority in every room where people are talking about the future of US rail. "Fourth largest" feels more future-oriented to me.
I implemented Patrick's language and am putting this on him to review/accept counter-proposals.

**Comment by PatrickCleary** [comment]
Yea, "oldest" definitely has a nice ring to it, but I think the size aspect gives us more authority.

**Comment by devinmatte** [comment]
I see the points, but also 4th just sounds unimportant to me. Fourth where most Americans probably can't even list 4 transit agencies. I know 2 years ago I wouldn't have been able to

**Comment by devinmatte** [comment]
"First" instead of "oldest"

**Comment by PatrickCleary** [comment]
https://transitmatters.slack.com/archives/GSJ6F35DW/p1685895104476899
