### ISSUE TITLE
Redesign line overview page: speed, ridership, slow zones, service

### ISSUE THREAD

**Issue by mcplanner** [transitmatters/t-performance-dash#611]

**Comment by mcplanner** [comment]
Y-axis is baseline value

**Comment by mcplanner** [comment]
Designs for desktop and mobile are up in [Figma](https://www.figma.com/file/bLBzzBX3r6tG2CoS6vWglD/Dashboard---V4?type=design&node-id=46-6603&t=YOyaJ87Wb4i0Emb2-0). They're mostly just screenshots of the existing page with comments for alignment, capitalization, and titles.
Kicking this over to Patrick for implementation.

**Comment by PatrickCleary** [comment]
I also think it'd be cool to have three pie charts at the top showing % change from 60-30 days ago compared with prev. 30 days.

`+4% from last month`
