### ISSUE TITLE
Update header to use our logo.

### ISSUE THREAD

**Issue by PatrickCleary** [transitmatters/t-performance-dash#615]
Use this:
![Screen Shot 2023-06-03 at 5 07 35 PM](https://github.com/transitmatters/t-performance-dash/assets/46229349/541ea33c-a2ef-4485-adbd-3d5ebcf839a3)

Not this:
![Screen Shot 2023-06-03 at 5 07 55 PM](https://github.com/transitmatters/t-performance-dash/assets/46229349/e51fab66-d52a-45f8-931e-14bb1b623622)

**Comment by devinmatte** [comment]
Is there a reason for this? I much prefer the current one

**Comment by PatrickCleary** [comment]
I do too, but Ruth @mcplanner made a good point that it's basically a copy of the T's logo. I think we either need a new favicon, or we have to use something else.

**Comment by devinmatte** [comment]
I mean it's an official logo of TransitMatters. I would check with @lawrencet1

**Comment by skaplan-dev** [comment]
Also much prefer the cleanliness of the one we have now 👍

**Comment by mcplanner** [comment]
The root issue here is that TransitMatters needs a professional brand redesign to minimize confusion with the MBTA itself and consolidate our visual resources. This is beyond the scope of the dashboard launch!

**Comment by lawrencet1** [comment]
Hi all, I need to make an official decision here: Please do not use the red T roundel on the dashboard. Please use either the fullmark or the wordmark only (leaning toward wordmark). I understand the red T roundel is currently part of the branding, but we are working to change it. I worry that having it on our Labs products will only cause further confusion about if this is a T project or ours. Thanks.
![Logo_wordmark_dark](https://github.com/transitmatters/t-performance-dash/assets/47332157/5cb31969-7eaf-444e-85ca-510f22321031)

**Comment by PatrickCleary** [comment]
We also would like to change the name from `data dashboard` to just `dashboard`.

**Comment by devinmatte** [comment]
We're currently using an svg file, and I'm real bad at editing svg's I'm finding out. Does someone have an svg without the `T` or should I just use a png?

**Comment by PatrickCleary** [comment]
![tm-logo-big](https://github.com/transitmatters/t-performance-dash/assets/46229349/8d667382-3c5e-46ce-a519-387c55bdfbcd)

Proportions are slightly different, may require some minor adjustment to the code

**Comment by devinmatte** [comment]
So I was seeing similar unclean lines in my edits. I feel like we shouldn't use an svg that'll render this way
<img width="142" alt="Screenshot 2023-06-07 at 1 26 53 PM" src="https://github.com/transitmatters/t-performance-dash/assets/9310513/921c7c4e-826e-4fc1-8c90-404e005b04c8">

**Comment by devinmatte** [comment]
For the future that would be great @lawrencet1. We got a better svg now, but just - to make sure

**Comment by lawrencet1** [comment]
How did you get an SVG of it on your own?

**Comment by lawrencet1** [comment]
![TM_wordmark_dark](https://github.com/transitmatters/t-performance-dash/assets/47332157/70990d34-d250-49bc-901e-6abfdd85930b)
Here's an SVG export direct from Illustrator. See how this looks.

**Comment by PatrickCleary** [comment]
Ruth made this for a temporary favicon until the rebrand is finished. 


![Image](https://github.com/transitmatters/t-performance-dash/assets/46229349/3b17fd67-15ae-4be5-ac8a-ca4d5305aac5)

**Comment by devinmatte** [comment]
Leaving favicon changes to #674
