### ISSUE TITLE
Line Selection Buttons

### ISSUE THREAD

**Issue by PatrickCleary** [transitmatters/t-performance-dash#625]
Make them look like this. (and get streetcar icon for green line)

![Image](https://github.com/transitmatters/t-performance-dash/assets/46229349/e64461fa-436b-4b0f-812f-609db6f2d9e9)

**Comment by idreyn** [comment]
IMO these icons look like LRT and I wonder if there's a more metro-looking one for the heavy rail lines.

**Comment by PatrickCleary** [comment]
https://fontawesome.com/search?q=train&o=r&m=free

<img width="418" alt="Screen Shot 2023-06-05 at 7 10 50 PM" src="https://github.com/transitmatters/t-performance-dash/assets/46229349/e458f017-4ae8-48f7-95f0-005c8f6b81b2">
