### ISSUE TITLE
Fix mobile controls on samsung (?) Devices

### ISSUE THREAD

**Issue by PatrickCleary** [transitmatters/t-performance-dash#626]
@nathan-weinberg 
Can you confirm the mobile controls are still wonky on your phone?

**Comment by nathan-weinberg** [comment]
@PatrickCleary LGTM, there's still a slight visual tick right when you start scrolling but very much improved!

**Comment by PatrickCleary** [comment]
Oh nice. I don't remember fixing it 😆
