### ISSUE TITLE
Application Crashes with client-side error

### ISSUE THREAD

**Issue by devinmatte** [transitmatters/t-performance-dash#627]
I've observed this often on the red line slowzones page

<img width="1512" alt="Screenshot 2023-06-05 at 8 19 37 PM" src="https://github.com/transitmatters/t-performance-dash/assets/9310513/a5953ff1-df3f-48e3-8b87-ec3483884128">

**Comment by PatrickCleary** [comment]
Do you know steps to reproduce it?

**Comment by devinmatte** [comment]
Refreshing the page in chrome usually does it for me. Not much else other than that

**Comment by PatrickCleary** [comment]
I'm guessing this was caused by the same issue you fixed today @devinmatte

**Comment by PatrickCleary** [comment]
Gonna assume this was fixed by #664 
Lmk if you think otherwise, Devin.

**Comment by devinmatte** [comment]
Yep I'll reopen if I find it again
