### ISSUE TITLE
Pages loading issues without query parameters

### ISSUE THREAD

**Issue by JNuss71** [transitmatters/t-performance-dash#641]
If you navigate directly to any single day data pages without the necessary URL parameters it will not load any data and won't have an option to select a date. The charts only show up if you put the parameters into the url or navigate to the desired page from either the Today page or one of the Line pages. After clicking "Single Day" from the broken page, the startDate is empty. Clicking "Multi Day" after that results in the endDate being empty and  the startDate being some invalid value.  

The way missing parameters is dealt with on Service, Slow Zones, and Speed is by printing a message "Select a date range to load graphs." albeit in an inconsistent way. Ridership doesn't have any message, but the date selector is available. 

This can be seen by navigating to http://localhost:3000/red/trips/ http://localhost:3000/red/ridership/ http://localhost:3000/red/slowzones/ and a few others

**Comment by PatrickCleary** [comment]
Yes, thanks for opening this. Definitely needs to be fixed. I think ideally by inputing default params when the URL is missing dates.

Could probably be dealt with at the level of the `<DateSelection/>` component by checking the NextJS Router `isReady` and then if the dates are missing, grab the appropriate default dates for the section.

Other option would be to make sure the date selector renders when date params are missing, then users can just input something. But I think I prefer the first option.

**Comment by PatrickCleary** [comment]
I am working on this, but will wait for #643 to merge since there's a lot of overlap
