### ISSUE TITLE
Graphical issues on Overview page

### ISSUE THREAD

**Issue by nathan-weinberg** [transitmatters/t-performance-dash#690]
**Describe the bug**
Seems the year is getting cut off here in the below screenshot (`Jan 8, 2`)

Also `peak` should probably be capitalized and have a comma in the middle to match the number formatting in the graph

**Screenshots**
![image](https://github.com/transitmatters/t-performance-dash/assets/31703736/b7964457-cc90-4bf5-88e0-49bddb8d8813)

**Device Info (please complete the following information):**
 - Device: Samsung Galaxy S20 FE 5G
 - OS: Android 
 - Browser: Firefox
 - Version: 114.1.1

**Comment by PatrickCleary** [comment]
Should be fixed by #707

**Comment by devinmatte** [comment]
@nathan-weinberg can you confirm this is fixed?
