### ISSUE TITLE
V4 Checklist Items

### ISSUE THREAD

**Issue by PatrickCleary** [transitmatters/t-performance-dash#718]
Some items in the checklist about accessibility, etc.

https://docs.google.com/document/d/1L3Z2I_vg7FLiZ9KIj7CNp5ock93doHZQ0ufw-utCi9Q/edit

**Comment by devinmatte** [comment]
<img width="754" alt="Screenshot 2023-07-06 at 7 44 35 PM" src="https://github.com/transitmatters/t-performance-dash/assets/9310513/e908cea4-dc34-4603-b66d-885dcb2b459a">
From lighthouse
