### ISSUE TITLE
TM logo in sidebar not appearing in Safari

### ISSUE THREAD

**Issue by idreyn** [transitmatters/t-performance-dash#759]
Safari...what are we going to do with you

![Image](https://user-images.githubusercontent.com/2208769/253609129-1bb0c28d-4fa4-4ee5-a476-8e9ff52e282b.png)

**Comment by PatrickCleary** [comment]
It appears in Safari for me 👀

**Comment by devinmatte** [comment]
What version of Safari/MacOS @idreyn ?

**Comment by mathcolo** [comment]
yeah looks OK here too
<img width="1214" alt="image" src="https://github.com/transitmatters/t-performance-dash/assets/193453/508234a0-d42a-49a5-9b6d-2621b93ce896">

**Comment by idreyn** [comment]
Closing as unreproducible.
