### ISSUE TITLE
Bug via feedback form

### ISSUE THREAD

**Issue by PatrickCleary** [transitmatters/t-performance-dash#795]
Via feedback form:

> I noticed that the dataviz for the slow zone data in segments is off when an existing slow zone is increased or an existing slow zone is decreased without being fully erased.  For example, Sullivan --> Community College (SB) is shown as a 117 second delay when it's actually a 237 second delay.  Likewise, Assembly --> Sullivan (SB) is shown as a 72 second delay when it's actually a 7 second delay at this point.

**Comment by devinmatte** [comment]
We now show latest and average, which should resolve this complaint mostly
