### ISSUE TITLE
Speed up frontend's http requests

### ISSUE THREAD

**Issue by mathcolo** [transitmatters/t-performance-dash#8]
Right now it feels like these happen serially. They should happen at the same time, or be coalesced into a single http request.

**Comment by austinjpaul** [comment]
I'm not seeing that this is the case- Testing on both Firefox and Chrome, it seems the requests are all issued at about the same time, and the graphs update whenever the responses come in. (Traveltimes is usually slower than the other two, and alerts is sometimes on the order of 30s- yikes!)

![image](https://user-images.githubusercontent.com/8498946/102173734-b3905180-3e69-11eb-9c4b-a06dc0dc653e.png)

**Comment by mathcolo** [comment]
Hmm, nice! Maybe we fixed this inadvertently, or perhaps it just wasn't an issue in the first place 👍 Closing...
