### ISSUE TITLE
Speed for station pairs

### ISSUE THREAD

**Issue by PatrickCleary** [transitmatters/t-performance-dash#803]
**Is your feature request related to a problem? Please describe.**
Show MPH speed for a station pair

**Describe the solution you'd like**
The first thing that would need to be done is to create a mapping of station pairs to distances. Currently we only have full-line distances.

**Additional context**
I (@PatrickCleary) have ideas on how this would look. If anyone wants to work on this, let me know and we can talk design.

**Comment by rudiejd** [comment]
I can take this one

**Comment by rudiejd** [comment]
https://github.com/transitmatters/data-ingestion/blob/bd84c4ccd6594ee83de86de6525334481cf370a8/ingestor/chalicelib/daily_speeds.py#L20 it looks like this data is already there, we just aren't storing it for each station pair

**Comment by rudiejd** [comment]
it seems like the [speed comes from the miles traveled divided by seconds of time aggregated in](https://github.com/rudiejd/t-performance-dash/blob/5c4f84477c8c543241343b4faa0425f080cb2184/server/chalicelib/speed.py#L73) `DeliveredTripMetrics`.  [we fetch all the data for each station pair,](https://github.com/transitmatters/data-ingestion/blob/bd84c4ccd6594ee83de86de6525334481cf370a8/ingestor/chalicelib/daily_speeds.py#L20) we just don't write it to any table. the easiest way to solve this seems to be a trip metrics table that includes data for each station pair to drive this new graph. I'll do the data ingestion work first and then work on the frontend stuff

**Comment by PatrickCleary** [comment]
Thanks for looking at this!

Is it possible we could calculate it when a stop-pair page is opened, rather than storing it all? I'm concerned it will be a lot of data to store.

**Comment by rudiejd** [comment]
no problem! My concern there would be getting rate limited, but I think we're fine as long as we only do this speed calculation on the trip metrics page for each line. I'll try coding up something to do that

**Comment by rudiejd** [comment]
There could also be a more sophisticated structure for storing this than just paid to pair trip seconds. For example, you could store the accumulation of average trip seconds and distance for each station in a direction, then use that data structure to calculate trip times / distances. For example inbound from alewife on the red line

{
Alewife: {
 miles_traveled: 0,
 trip_seconds_inbound: 0
}
...
{
Kendall: {
miles_traveled_inbound: dist(alewife, Kendall)
trip_seconds_inbound: trip_seconds(alewife, Kendall)
}, 
Charles: {
   miles_traveled_inbound: dist(alewife, Charles)
   trip_seconds_inbound: trip_seconds(alewife, Charles)
...



}

Then to calculate Kendall to Charles, you subtract the charles_miles_traveled - kendall_miles_traveled. Of course, your table would have to have distance and time for every route terminus. But then you only need to store a row for each station

**Comment by PatrickCleary** [comment]
We had been talking about storing travel times in a db (rather than as CSVs like we currently do). Your strategy sounds like a good way to reduce the storage while doing that. It's been awhile since I've looked at this, but I would think in this case it is a simple sum + median calculation on the metrics with a constant factor of the distance between tracks. Which makes me lean towards using a frontend ad hoc calculation.

Something else to consider – there are dwells where the train is stopped at a certain station. I _believe_ this time is included in the overall travel times, but not the station to station.

i.e. if you have a station ordering like A -> B -> C
and the train takes 1 minute from A -> B and 2 minutes from B -> C
Then A -> C is not necessarily 3 minutes, because the time train spent at B is not included until you look at the overall trip.

**Comment by rudiejd** [comment]
Ah, the dwells definitely throw a wrench into things 🙃 
Yep agree calling the API directly will be the easiest to start with, then if rate limiting becomes an issue we can either add some cooloff mechanism for changing station on the frontend or revisit storing things
