### ISSUE TITLE
Show time prediction accuracy

### ISSUE THREAD

**Issue by devinmatte** [transitmatters/t-performance-dash#822]
**Is your feature request related to a problem? Please describe.**
We should show how accurate the time predictions are for the trains

**Describe the solution you'd like**
Show a graph or two showing how accurate (or really, inaccurate) the time predictions are for trains

**Additional context**

Data available here
https://mbta-massdot.opendata.arcgis.com/datasets/rapid-transit-and-bus-prediction-accuracy-data/explore

**Comment by idreyn** [comment]
Here is the code I used to make some initial graphs for this: https://github.com/transitmatters/prediction-accuracy

**Comment by devinmatte** [comment]
Data is now being ingested into Dynamo https://github.com/transitmatters/data-ingestion/pull/46

We can pull this now easily
