### ISSUE TITLE
Watermark Landing Charts

### ISSUE THREAD

**Issue by lawrencet1** [transitmatters/t-performance-dash#826]
**Is your feature request related to a problem? Please describe.**
Noticed that the landing charts aren't watermarked when Chris tweeted screenshots. We want our branding in all screenshots of charts. https://twitter.com/friendchristoph/status/1689809902842097664

**Describe the solution you'd like**
Add the standard watermark.

**Additional context**
![image](https://github.com/transitmatters/t-performance-dash/assets/47332157/c5839fce-c402-4639-afbc-0f3633f5146c)

**Comment by PatrickCleary** [comment]
Completed in #828
