### ISSUE TITLE
End date on slowzone link should provide 7 extra days of context.

### ISSUE THREAD

**Issue by austinjpaul** [transitmatters/t-performance-dash#844]
https://github.com/transitmatters/t-performance-dash/blob/555fd54bbefe5d389943b822e33fc1c80fc054c4/modules/slowzones/charts/LineSegments.tsx#L131

It helps the slowzone stand out more.
We can't provide 7 full days, ofcourse, if the end of the SZ was less than 7 days ago.

**Comment by austinjpaul** [comment]
We also shouldn't provide links to more data than can be loaded. In the past we truncated the startDate in that scenario.

**Comment by cdwhitt** [comment]
@devinmatte @austinjpaul Can you help me confirm if this has been worked on? Just now getting around to it. Looks like there were changes made a handful of months ago, but not sure if there's more to do.

**Comment by austinjpaul** [comment]
looks like this was already done

**Comment by nathan-weinberg** [comment]
If it's done, we can close the issue :slightly_smiling_face:
