### ISSUE TITLE
Slight overview rearrange

### ISSUE THREAD

**Issue by PatrickCleary** [transitmatters/t-performance-dash#862]
On Red, Orange, blue, the alerts/accessiblity widgets are in their own row on desktop. On the green line, since there are no SZs, they move up a row. I think they should be separated. Would also be good to have a very subtle visual indicator to show they are a separate section.
<img width="1440" alt="Screenshot 2023-09-08 at 10 36 49 AM" src="https://github.com/transitmatters/t-performance-dash/assets/46229349/1d5cb83b-9d17-4651-b78a-d4e6c1e4f558">

**Comment by nathan-weinberg** [comment]
Does https://github.com/transitmatters/t-performance-dash/pull/864 resolve this or is there anything left we want to do before closing?
