### ISSUE TITLE
Remove padding so that charts can be wider on mobile

### ISSUE THREAD

**Issue by idreyn** [transitmatters/t-performance-dash#903]
Here's a screenshot of an overview page on mobile:

![image](https://github.com/transitmatters/t-performance-dash/assets/2208769/2cf6b977-5523-4c12-b21d-4709e360e9a3)

Note three kinds of horizontal padding:

1. Around the wrapper (white box on grey)
2. Within the wrapper
3. Between the y-axis label and the chart

The result is that there's relatively little space for the charts themselves. We should consider adding mobile styles to reduce this padding in some combination, and give it back to the widget contents.

**Comment by bhanuteja-03** [comment]
@idreyn I want to work on this issue, Please assign it to me
I have two approaches,
1) my thought process is to reduce the padding values by half for both outer and inner padding.
2) remove the outer padding, that is to remove grey area.

Or if you have any idea let me know, I will work on it

**Comment by nathan-weinberg** [comment]
@bhanuteja-03 assigned it to you! let me know if you're still interested :+1: @idreyn did you have any thoughts on the above suggestions?
