### ISSUE TITLE
Coloring on Overview date selector component

### ISSUE THREAD

**Issue by PatrickCleary** [transitmatters/t-performance-dash#914]
**Describe the bug**
The overview date selector colors are off. It looks like it's improperly reading the line color and applying DEFAULT colors.

![Screenshot 2023-12-23 at 2 31 02 PM](https://github.com/transitmatters/t-performance-dash/assets/46229349/3785dc47-7367-43f0-84ae-1d2129694587)

**To Reproduce**
go to:
https://dashboard.transitmatters.org/red/
hover/click on a date range

**Expected behavior**
Should be similar coloring to other buttons

**Comment by NJacksonDev** [comment]
When you hover over a button, do you want the color to change to black background with white text (same color scheme as the selected date)?

**Comment by bhanuteja-03** [comment]
@PatrickCleary, I want to work on this issue. can you give more insights to what should I do, like change which colors( weather the hovered element color or any other).
