### ISSUE TITLE
Determine bus routes to support + update constants.js

### ISSUE THREAD

**Issue by mathcolo** [transitmatters/t-performance-dash#96]
As I noticed in https://github.com/transitmatters/t-performance-dash/pull/93 — we don't have data for all routes.

Whoever picks this up needs to determine, of the routes we have available, which to support, and then update `src/constants.js` with stop data for those.

Note: This is a manual process because the data is so sparse. i.e. for the 57 we only have the following directions and stops available—therefore needs to be human curated.

```
{
    "57": {
        "979": [
            0
        ],
        "899": [
            1,
            0
        ],
        "987": [
            0
        ],
        "1807": [
            0
        ],
        "931": [
            1
        ],
        "912": [
            1
        ],
        "918": [
            1
        ],
        "959": [
            0
        ],
        "966": [
            0
        ],
        "900": [
            1,
            0
        ],
        "903": [
            1
        ],
        "937": [
            1
        ],
        "954": [
            0
        ],
        "9780": [
            0
        ],
        "926": [
            1
        ],
        "913": [
            1
        ],
        "973": [
            0
        ],
        "11780": [
            0
        ]
    }
}

```

**Comment by austinjpaul** [comment]
Routes 1 and 28 already supported.
Consider Key Bus Routes. Alternatively, just go down the list by ridership count.
Next up: 66, 114/116/117 (this corridor and others can be done by 'branching'), 57/57A (ew), 23, 111.
Also, SL1/2/3 and SL4/5?

**Comment by austinjpaul** [comment]
Above is done. Next ones by ridership numbers:
SL1/2/3, SL4/5 (if possible)
* 39
104/109
* 32
* 22 (columbus bus lane)
61/70/170
16
86
34
* 77 (mass ave buslane focus?)

* key route. other key routes: 15, 71, 73
