### ISSUE TITLE
Upload events files for curated bus routes

### ISSUE THREAD

**Issue by mathcolo** [transitmatters/t-performance-dash#97]
(Requires https://github.com/transitmatters/t-performance-dash/issues/96)

Once we've decided what bus routes and stations to support, we need to actually upload events for those. You'll want to use [the bus generator tool](https://github.com/transitmatters/t-performance-dash/pull/93) in combination with the [bus data from the MassDOT portal](https://mbta-massdot.opendata.arcgis.com/datasets/mbta-bus-arrival-departure-times-2020/about) to do this.

By default bus2train will generate for all routes, but [there's a debug override](https://github.com/transitmatters/t-performance-dash/pull/93/files#diff-20e5237caf1167da6734d48bec2a384fefb18d3fc3ee240fb207b897f2777d26R116) that can be used to restrict to certain routes. And sorry, that should really be a command-line argument!

**Comment by austinjpaul** [comment]
handled in #107
